version: '2'
services:
  hackmdPostgres:
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=hackmdpass
      - POSTGRES_DB=hackmd
  hackmd:
    image: hackmdio/hackmd:0.4.3
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=hackmdpass
    links:
      - hackmdPostgres
    ports:
      - "3000:3000"
    depends_on:
      - hackmdPostgres
